version: '3.1'

services:
  pleroma:
    image: git.pleroma.social:5050/pleroma/pleroma:stable
    container_name: "pleroma"
    hostname: "pleroma"
    restart: always
    depends_on:
      - pleroma-db
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./config.exs:/var/lib/pleroma/config.exs
      - ./static:/var/lib/pleroma/static
      - pleroma-uploads:/var/lib/pleroma/uploads
    environment:
      DB_USER: pleroma
      DB_PASS: '##REPLACE-ME##'
      DB_HOST: pleroma-db
      DB_NAME: pleroma
      INSTANCE_NAME: My Pleroma
      ADMIN_EMAIL: pleroma+admin@example.com
      NOTIFY_EMAIL: pleroma+admin@example.com
      DOMAIN: social.example.com
      PORT: 4000

  pleroma-db:
    image: postgres:15.1-alpine
    container_name: "pleroma-db"
    hostname: "pleroma-db"
    restart: always
    # ports:
    #   - "127.0.0.1:5432:5432"
    volumes:
      - pleroma-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: '##REPLACE-ME##'

volumes:
  pleroma-db-data:
  pleroma-uploads:
